cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

language: ruby

rvm:
- 2.5

install: gem install jekyll jekyll-paginate jemoji html-proofer
script: jekyll serve --baseurl "" --detach && htmlproofer ./_site --disable-external --allow_hash_href --empty-alt-ignore

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true JEKYLL_ENV=production
